source: .
destination: ./_site

title: Александр Шелеметьев
slogan: компьютеры - сети - безопасность

person:
  name: Александр Викторович Шелеметьев
  email: glaf@mail.ru
  phone: +7 904 991-5035
  tox: D0E2F9BEC255BF365371D9533FCC00DCE2A95D16038E893D4F41C69503434C67B59C1B0BBC66

author:
    year: 2013
    name: Александр Шелеметьев


