source: .
destination: ./_site

title: Александр Шелеметьев
slogan: компьютеры - сети - безопасность

person:
  name: Александр Викторович Шелеметьев
  email: glaf@mail.ru
  phone: +7 965 823-9468

author:
    year: 2013-2017
    name: Александр Шелеметьев


