source: .
destination: ./_site

title: Александр Шелеметьев
slogan: компьютеры - сети - безопасность

person:
  name: Александр Викторович Шелеметьев
  email: glaf@mail.ru
  phone: +7 904 991-5035
  tox: 6C1F1CD7FC96E1F803D0360D8A96E0088700FB6F5954C7DA8391081D960ACC60F049BF9A4E31

author:
    year: 2013
    name: Александр Шелеметьев


