markdown: kramdown

source: .
destination: ./_site

title: Александр Шелеметьев
slogan: компьютеры - сети - безопасность

person:
  name: Александр Викторович Шелеметьев
<<<<<<< HEAD
  email: glaf@mail.ru
=======
  email: ex.lxndr@gmail.com
>>>>>>> parent of 7be7bef... coming back
  phone: +7 965 823-9468
  tox: 51E16AB725675D410B90776FE5B13A250FF180C704EFA075FE80BA487357077DDBCED0C6F05D

author:
<<<<<<< HEAD
    year: 2013-2017
=======
    year: 2013-2018
>>>>>>> parent of 7be7bef... coming back
    name: Александр Шелеметьев


