markdown: kramdown

source: .
destination: ./_site

title: Александр Шелеметьев
slogan: компьютеры - сети - безопасность

person:
  name: Александр Викторович Шелеметьев
  email: ex.lxndr@gmail.com
  phone: +7 965 823-9468

author:
    year: 2013-2018
    name: Александр Шелеметьев


